export const checklist = [
  { text: 'Miros geam baie (posibil asezare geam la ghena interioara)', checked: true },
  { text: 'Starea scarii (jeg, lucruri lasate pe scara, interfon functional). Verificare geamuri vecini deasupra și dedesubt', checked: true },
  { text: 'Verificat usa de intrare (inchidere, urme de lovituri)', checked: true },
  { text: 'Lista de intretinere - restantieri, aproximativ plata lunara intretinere', checked: true },
  { text: 'Infiltratii si/sau mucegai (miros suspect, parfum puternic)', checked: true },
  { text: 'Verificare risc seismic (bulina bloc)', checked: true },
  { text: 'Instalatie electrica verificata (prize, panou, etc)', checked: true },
  { text: 'Pornit apa calda (viteza, presiune), verificat calorifere', checked: true },
  { text: 'Instalatii, tevi, scurgeri verificate (miros din scurgeri)', checked: true },
  { text: 'Calitatea aerului in zona si apartament cu geamul deschis', checked: true },
  { text: 'Orientare - est... se vede vecinul pe geam?', checked: true },
  { text: 'Verificat grosime pereti, stare pereti', checked: true },
  { text: 'Locuri de parcare? Achiziționare, închiriere, licitație primărie', checked: true },
  { text: 'Boschetari / dubiosi in zona', checked: true },
  { text: 'Apartament langa lift? Stare lift (zgomot, etc)', checked: true },
  { text: 'Verificat acte (an constructie, releveu, metri utili)', checked: true },
  { text: 'Verificat termopane / ferestre (închidere, calitate)', checked: true },
  { text: 'Unde sunt apometrele, repartitoarele, de unde se inchide apa, gazul?', checked: true },
  { text: 'Ce izolatie are apartamentul?', checked: true },
  { text: 'Ce tip de parchet e? Trebuie schimbat?', checked: true },
  { text: 'Boxa / bunker disponibil? Poate fi vizitată? Inclus în releveu?', checked: true },
  { text: 'Ce operator de cablu, internet există în bloc?', checked: true },
  { text: 'Proiect gaze la zi? Posibilitate centrală?', checked: true },
  { text: 'Cadastrul este la zi? Include modificări?', checked: true },
  { text: 'Izolare fonică? Se aude din scară în apartament?', checked: true },
  { text: 'Semnal telefon în apartament?', checked: true },
  { text: 'Contract: se specifică detalii (mobilier, electrocasnice, etc.)', checked: true }
];
