import {Injectable} from '@angular/core';
import {Picture} from "../model/picture";
import {Observable, of} from "rxjs";

@Injectable({
  providedIn: 'root'
})
export class PicturesService {
  constructor() { }

  getPictures(): Observable<Picture[]> {
    const sortedPictures = [...pictures].sort((a, b) => a.id - b.id); // Using spread to avoid mutating the original array
    return of(sortedPictures);
  }

  getPictureById(id: number): Observable<Picture | null> {
    const picture = pictures.find(p => p.id === id);
    return of(picture || null);
  }
}

export const pictures: Picture[] = [
  new Picture(1,
    'stefania-ionescu-targoviste-min.jpg',
    null,
    '18th of April, 2024',
    'Târgoviște, România',
    'https://maps.app.goo.gl/8GWzhKLjFKUkHWyJA',
    'Ștefania Ionescu',
    'https://www.instagram.com/steff_06_/',
    'f/5.6, 1/180 sec, ISO 160. On-camera flash.'
    ),
  new Picture(25,
    'stefania-ionescu-leu-c-min.jpg',
    null,
    '18th of April, 2024',
    'The Lion Complex',
    'https://maps.app.goo.gl/CnRDSFfyjTTqtEHA8',
    'Ștefania Ionescu',
    'https://www.instagram.com/steff_06_/',
    'f/2.8, 1/180 sec, ISO 200. Backlit & off camera flash with umbrella diffuser.'
    ),
  new Picture(32,
    'bucharest-court-min.jpg',
    null,
    '20th of April, 2024',
    'Bucharest Court',
    'https://maps.app.goo.gl/YBw9PkbhCEg5Zom37',
    null,
    null,
    'f/5, 1/4000 sec, ISO 500.'),
  new Picture(40,
    'national-library-of-romania-min.jpg',
    null,
    '20th of April, 2024',
    'National Library of Romania',
    'https://maps.app.goo.gl/QDYRHBQb5gfhwXgk6',
    null,
    null,
    'f/2.2, 1/2000 sec, ISO 100.'),
  new Picture(42,
    'double-bmws-min.jpg',
    null,
    '20th of April, 2024',
    'Chamber of Commerce and Industry',
    'https://maps.app.goo.gl/TyVhoVUJh3Wucvij8',
    null,
    null,
    'f/2.2, 1/2000 sec, ISO 400.'),
  new Picture(15,
    'chamber-of-commerce-and-industry-min.jpg',
    null,
    '20th of April, 2024',
    'Chamber of Commerce and Industry',
    'https://maps.app.goo.gl/TyVhoVUJh3Wucvij8',
    null,
    null,
    'f/2.2, 1/2000 sec, ISO 100.'),
  new Picture(29,
    'blvd-mircea-voda-min.jpg',
    null,
    '20th of April, 2024',
    'Mircea Vodă Boulevard',
    'https://maps.app.goo.gl/oLGQKc9s3FZJ2UTQ7',
    null,
    null,
    'f/2.2, 1/2000 sec, ISO 100.'),
  new Picture(38,
    'jandarmeria-truck-1-min.jpg',
    null,
    '20th of April, 2024',
    'Union Boulevard',
    'https://maps.app.goo.gl/z9qokV8ju6y6fmbZA',
    null,
    null,
    'f/2.2, 1/2000 sec, ISO 125.'),
  new Picture(3,
    'jandarmeria-truck-2-min.jpg',
    null,
    '20th of April, 2024',
    'Union Boulevard',
    'https://maps.app.goo.gl/z9qokV8ju6y6fmbZA',
    null,
    null,
    'f/1.8, 1/1000 sec, ISO 100.'),
  new Picture(23,
    'color-run-playful-child-min.jpg',
    null,
    '20th of April, 2024',
    'Color Run',
    'https://maps.app.goo.gl/PQQVi5ox9qD3Ashv9',
    null,
    null,
    'f/2.2, 1/2000 sec, ISO 200.'),
  new Picture(26,
    'jandarmeria-crosswalk-min.jpg',
    null,
    '20th of April, 2024',
    'Color Run',
    'https://maps.app.goo.gl/PQQVi5ox9qD3Ashv9',
    null,
    null,
    'f/1.8, 1/2500 sec, ISO 160.'),
  new Picture(11,
    'color-run-finish-line-min.jpg',
    null,
    '20th of April, 2024',
    'Color Run',
    'https://maps.app.goo.gl/PQQVi5ox9qD3Ashv9',
    null,
    null,
    'f/1.8, 1/2500 sec, ISO 100.'),
  new Picture(35,
    'jandarmeria-back-shot-1-min.jpg',
    null,
    '20th of April, 2024',
    'Color Run',
    'https://maps.app.goo.gl/PQQVi5ox9qD3Ashv9',
    null,
    null,
    'f/1.8, 1/2000 sec, ISO 250.'),
  new Picture(20,
    'color-run-back-shot-1-min.jpg',
    null,
    '20th of April, 2024',
    'Color Run',
    'https://maps.app.goo.gl/PQQVi5ox9qD3Ashv9',
    null,
    null,
    'f/1.8, 1/2000 sec, ISO 125.'),
  new Picture(14,
    'bike-1-min.jpg',
    null,
    '20th of April, 2024',
    'Union Boulevard',
    'https://maps.app.goo.gl/jrqEgrzxVspMfSTM9',
    null,
    null,
    'f/1.8, 1/800 sec, ISO 250.'),
  new Picture(5,
    'tesla-1-min.jpg',
    null,
    '20th of April, 2024',
    'Union Boulevard',
    'https://maps.app.goo.gl/yfwhpKDBGY1nrmtc8',
    null,
    null,
    'f/1.8, 1/400 sec, ISO 100.'),
  new Picture(4,
    'garlic-1-min.jpg',
    null,
    '20th of April, 2024',
    'Local Farmers\' Market',
    'https://maps.app.goo.gl/f44jdQatbMr6R7Tj9',
    null,
    null,
    'f/1.8, 1/1600 sec, ISO 160.'),
  new Picture(22,
    'bike-girl-1-min.jpg',
    null,
    '20th of April, 2024',
    'Union Boulevard',
    'https://maps.app.goo.gl/J2LBhTnQ6nfQwMRr9',
    null,
    null,
    'f/1.8, 1/1250 sec, ISO 250.'),
  new Picture(33,
    'old-man-1-min.jpg',
    null,
    '20th of April, 2024',
    'Union Boulevard',
    'https://maps.app.goo.gl/f3MqbLFxuE7KsaMG8',
    null,
    null,
    'f/1.8, 1/1250 sec, ISO 100.'),
  new Picture(13,
    'union-boulevard-1-min.jpg',
    null,
    '20th of April, 2024',
    'Union Boulevard',
    'https://maps.app.goo.gl/f3MqbLFxuE7KsaMG8',
    null,
    null,
    'f/4, 1/1000 sec, ISO 100.'),
  new Picture(21,
    'union-boulevard-2-min.jpg',
    null,
    '20th of April, 2024',
    'Union Boulevard',
    'https://maps.app.goo.gl/f3MqbLFxuE7KsaMG8',
    null,
    null,
    'f/4.5, 1/640 sec, ISO 100.'),
  new Picture(18,
    'bmw-1-min.jpg',
    null,
    '20th of April, 2024',
    'Union Boulevard',
    'https://maps.app.goo.gl/6nY3XAcv7G5CzPVb6',
    null,
    null,
    'f/1.8, 1/400 sec, ISO 400.'),
  new Picture(16,
    'guy-waiting-flower-1-min.jpg',
    null,
    '20th of April, 2024',
    'Union Plaza',
    'https://maps.app.goo.gl/pKVSidFra17wrP86A',
    null,
    null,
    'f/3.2, 1/250 sec, ISO 100.'),
  new Picture(49,
    'guy-on-bike-1-min.jpg',
    null,
    '20th of April, 2024',
    'Union Plaza',
    'https://maps.app.goo.gl/vyiQHuiZMkpcQpQg7',
    null,
    null,
    'f/3.2, 1/250 sec, ISO 100.'),
  new Picture(8,
    'guy-back-shot-1-min.jpg',
    null,
    '20th of April, 2024',
    'Old Town',
    'https://maps.app.goo.gl/em2HScuwVp86VLWc9',
    null,
    null,
    'f/1.8, 1/800 sec, ISO 100.'),
  new Picture(10,
    'accordion-player-min.jpg',
    null,
    '20th of April, 2024',
    'Old Town',
    'https://maps.app.goo.gl/CZpC9P2EE3W5wJpTA',
    null,
    null,
    'f/3.2, 1/200 sec, ISO 500.'),
  new Picture(28,
    'street-performer-1-min.jpg',
    null,
    '20th of April, 2024',
    'Old Town',
    'https://maps.app.goo.gl/5NDjPqsgXzo6DJJT7',
    null,
    null,
    'f/1.8, 1/1000 sec, ISO 320.'),
  new Picture(12,
    'guy-tunnel-1-min.jpg',
    null,
    '20th of April, 2024',
    'Old Town',
    'https://maps.app.goo.gl/5NDjPqsgXzo6DJJT7',
    null,
    null,
    'f/1.8, 1/500 sec, ISO 160.'),
  new Picture(6,
    'street-performer-2-min.jpg',
    null,
    '20th of April, 2024',
    'Victory Street',
    'https://maps.app.goo.gl/KFBdsabApQnhEAh36',
    null,
    null,
    'f/4, 1/640 sec, ISO 250.'),
  new Picture(30,
    'palace-hall-min.jpg',
    null,
    '20th of April, 2024',
    'The Palace Hall',
    'https://maps.app.goo.gl/8Z1VGR9VoWRa8KrN8',
    null,
    null,
    'f/4, 1/1000 sec, ISO 200.'),
  new Picture(19,
    'street-performer-3-min.jpg',
    null,
    '20th of April, 2024',
    'Victory Street',
    'https://maps.app.goo.gl/LQciTZtApnDyStHbA',
    null,
    null,
    'f/1.8, 1/800 sec, ISO 250.'),
  new Picture(2,
    'jandarmeria-back-shot-2-min.jpg',
    null,
    '20th of April, 2024',
    'Victory Street',
    'https://maps.app.goo.gl/mJRWJKFsF2f2zAEG6',
    null,
    null,
    'f/1.8, 1/1250 sec, ISO 250.'),
  new Picture(31,
    'bancorex-headquarters-1-min.jpg',
    null,
    '20th of April, 2024',
    'Bancorex Headquarters',
    'https://maps.app.goo.gl/v4BrzBkJHeYwByis5',
    null,
    null,
    'f/4, 1/400 sec, ISO 125.'),
  new Picture(34,
    'bancorex-headquarters-2-min.jpg',
    null,
    '20th of April, 2024',
    'Bancorex Headquarters',
    'https://maps.app.goo.gl/v4BrzBkJHeYwByis5',
    null,
    null,
    'f/4, 1/400 sec, ISO 125.'),
  new Picture(27,
    'national-museum-of-romanian-history-1-min.jpg',
    null,
    '20th of April, 2024',
    'National Museum of Romanian History',
    'https://maps.app.goo.gl/QR8J4ucDQSFz8ocJ9',
    null,
    null,
    'f/1.8, 1/500 sec, ISO 3200.'),
  new Picture(36,
    'old-town-1-min.jpg',
    null,
    '20th of April, 2024',
    'Old Town',
    'https://maps.app.goo.gl/eWTzKTxqPBqE6RPGA',
    null,
    null,
    'f/1.8, 1/400 sec, ISO 320.'),
  new Picture(48,
    'union-plaza-1-min.jpg',
    null,
    '20th of April, 2024',
    'Union Plaza',
    'https://maps.app.goo.gl/jxoHwJGAnMmuAHae8',
    null,
    null,
    'f/1.8, 1/400 sec, ISO 400.'),
  new Picture(7,
    'union-plaza-2-min.jpg',
    null,
    '20th of April, 2024',
    'Union Plaza',
    'https://maps.app.goo.gl/jxoHwJGAnMmuAHae8',
    null,
    null,
    'f/1.8, 1/400 sec, ISO 1250.'),
  new Picture(39,
    'union-plaza-3-min.jpg',
    null,
    '20th of April, 2024',
    'Union Plaza',
    'https://maps.app.goo.gl/jxoHwJGAnMmuAHae8',
    null,
    null,
    'f/1.8, 1/400 sec, ISO 160.'),
  new Picture(41,
    'union-plaza-4-min.jpg',
    null,
    '20th of April, 2024',
    'Union Plaza',
    'https://maps.app.goo.gl/jxoHwJGAnMmuAHae8',
    null,
    null,
    'f/1.8, 1/400 sec, ISO 2500.'),
  new Picture(47,
    'union-plaza-5-min.jpg',
    null,
    '20th of April, 2024',
    'Union Plaza',
    'https://maps.app.goo.gl/1pJAZcB2cBTJhVw76',
    null,
    null,
    'f/1.8, 1/80 sec, ISO 1250.'),
  new Picture(9,
    'national-museum-of-romanian-history-2-min.jpg',
    null,
    '20th of April, 2024',
    'National Museum of Romanian History',
    'https://maps.app.goo.gl/QR8J4ucDQSFz8ocJ9',
    null,
    null,
    'f/1.8, 1/60 sec, ISO 500.'),
  new Picture(17,
    'color-run-back-shot-2-min.jpg',
    null,
    '20th of April, 2024',
    'Color Run',
    'https://maps.app.goo.gl/PQQVi5ox9qD3Ashv9',
    null,
    null,
    'f/2.5, 1/2000 sec, ISO 640.'),
  new Picture(43,
    'basarab-passage-1-min.jpg',
    null,
    '21th of April, 2024',
    'Basarab Passage',
    'https://maps.app.goo.gl/4ZoneC3t4yaksRt47',
    null,
    null,
    'f/4.5, 1/800 sec, ISO 100.'),
  new Picture(44,
    'basarab-passage-2-min.jpg',
    null,
    '21th of April, 2024',
    'Basarab Passage',
    'https://maps.app.goo.gl/4ZoneC3t4yaksRt47',
    null,
    null,
    'f/3.2, 1/800 sec, ISO 100.'),
  new Picture(45,
    'basarab-passage-3-min.jpg',
    null,
    '21th of April, 2024',
    'Basarab Passage',
    'https://maps.app.goo.gl/4ZoneC3t4yaksRt47',
    null,
    null,
    'f/3.2, 1/800 sec, ISO 1000.'),
  new Picture(46,
    'basarab-passage-4-min.jpg',
    null,
    '21th of April, 2024',
    'Basarab Passage',
    'https://maps.app.goo.gl/4ZoneC3t4yaksRt47',
    null,
    null,
    'f/3.2, 1/800 sec, ISO 100.'),
  new Picture(37,
    'basarab-passage-5-min.jpg',
    null,
    '21th of April, 2024',
    'Basarab Passage',
    'https://maps.app.goo.gl/4ZoneC3t4yaksRt47',
    null,
    null,
    'f/4, 1/1600 sec, ISO 100.'),
  new Picture(50,
    'basarab-passage-6-min.jpg',
    null,
    '21th of April, 2024',
    'Basarab Passage',
    'https://maps.app.goo.gl/4ZoneC3t4yaksRt47',
    null,
    null,
    'f/4, 1/800 sec, ISO 200.'),
  new Picture(24,
    'bucharest-north-train-station-1-min.jpg',
    null,
    '21th of April, 2024',
    'Bucharest North Train Station',
    'https://maps.app.goo.gl/HZRDrN5A8pAWSc227',
    null,
    null,
    'f/1.8, 1/3200 sec, ISO 160.'),
];
