import {Injectable} from '@angular/core';
import {Picture} from "../model/picture";
import {Observable, of} from "rxjs";

@Injectable({
  providedIn: 'root'
})
export class PicturesService {
  constructor() { }

  getPictures(): Observable<Picture[]> {
    return of(pictures);
  }

  getPictureById(id: number): Observable<Picture | null> {
    const picture = pictures.find(p => p.id === id);
    return of(picture || null);
  }
}

export const pictures: Picture[] = [
  new Picture(1,
    'lavinia-popa-afi-cotroceni-leu-c.jpg',
    'The first snapshot I took with my new mirrorless camera features Lavinia against the backdrop of the AFI Cotroceni Sphere, perched atop our student residence roof. Illuminated solely by natural light, I improvised with a phone flash to fill in the shadows, as professional lighting gear wasn\'t yet part of my kit.',
    '11th of April, 2024',
    'The Lion Complex',
    'https://maps.app.goo.gl/WZ3KBwhREhcmRgNP8' ,
    'Lavinia Popa',
    'https://www.instagram.com/laviniapopa.03/',
    'f/1.8, 1/50 sec, ISO 12800.'),
  new Picture(2,
    'stefania-ionescu-leu-c.jpg',
    'This image captures my early exploration into studio-like portrait photography, equipped with my newly acquired lighting setup, albeit not perfect. It included a light positioned behind Ștefania, an off-camera flash with an umbrella diffuser, and a wireless trigger on the camera.',
    '18th of April, 2024',
    'The Lion Complex',
    'https://maps.app.goo.gl/CnRDSFfyjTTqtEHA8',
    'Ștefania Ionescu',
    'https://www.instagram.com/steff_06_/',
    'f/2.8, 1/180 sec, ISO 200. Backlit & off camera flash with umbrella diffuser.'
    ),
  new Picture(3,
    'national-library-of-romania.jpg',
    null,
    '20th of April, 2024',
    'National Library of Romania',
    'https://maps.app.goo.gl/QDYRHBQb5gfhwXgk6',
    null,
    null,
    'f/2.2, 1/2000 sec, ISO 100.'),
  new Picture(4,
    'double-bmws.jpg',
    null,
    '20th of April, 2024',
    'Chamber of Commerce and Industry',
    'https://maps.app.goo.gl/TyVhoVUJh3Wucvij8',
    null,
    null,
    'f/2.2, 1/2000 sec, ISO 400.'),
  new Picture(5,
    'chamber-of-commerce-and-industry.jpg',
    null,
    '20th of April, 2024',
    'Chamber of Commerce and Industry',
    'https://maps.app.goo.gl/TyVhoVUJh3Wucvij8',
    null,
    null,
    'f/2.2, 1/2000 sec, ISO 100.'),
  new Picture(6,
    'blvd-mircea-voda.jpg',
    null,
    '20th of April, 2024',
    'Mircea Vodă Boulevard',
    'https://maps.app.goo.gl/oLGQKc9s3FZJ2UTQ7',
    null,
    null,
    'f/2.2, 1/2000 sec, ISO 100.'),
  new Picture(7,
    'jandarmeria-truck-1.jpg',
    null,
    '20th of April, 2024',
    'Union Boulevard',
    'https://maps.app.goo.gl/z9qokV8ju6y6fmbZA',
    null,
    null,
    'f/2.2, 1/2000 sec, ISO 125.'),
  new Picture(8,
    'jandarmeria-truck-2.jpg',
    null,
    '20th of April, 2024',
    'Union Boulevard',
    'https://maps.app.goo.gl/z9qokV8ju6y6fmbZA',
    null,
    null,
    'f/1.8, 1/1000 sec, ISO 100.'),
  new Picture(9,
    'color-run-playful-child.jpg',
    null,
    '20th of April, 2024',
    'Color Run',
    'https://maps.app.goo.gl/PQQVi5ox9qD3Ashv9',
    null,
    null,
    'f/2.2, 1/2000 sec, ISO 200.'),
  new Picture(10,
    'jandarmeria-crosswalk.jpg',
    null,
    '20th of April, 2024',
    'Color Run',
    'https://maps.app.goo.gl/PQQVi5ox9qD3Ashv9',
    null,
    null,
    'f/1.8, 1/2500 sec, ISO 160.'),
  new Picture(11,
    'color-run-finish-line.jpg',
    null,
    '20th of April, 2024',
    'Color Run',
    'https://maps.app.goo.gl/PQQVi5ox9qD3Ashv9',
    null,
    null,
    'f/1.8, 1/2500 sec, ISO 100.'),
  new Picture(12,
    'jandarmeria-back-shot-1.jpg',
    null,
    '20th of April, 2024',
    'Color Run',
    'https://maps.app.goo.gl/PQQVi5ox9qD3Ashv9',
    null,
    null,
    'f/1.8, 1/2000 sec, ISO 250.'),
  new Picture(13,
    'color-run-back-shot-1.jpg',
    null,
    '20th of April, 2024',
    'Color Run',
    'https://maps.app.goo.gl/PQQVi5ox9qD3Ashv9',
    null,
    null,
    'f/1.8, 1/2000 sec, ISO 125.'),
  new Picture(13,
    'bucharest-court.jpg',
    null,
    '20th of April, 2024',
    'Bucharest Court',
    'https://maps.app.goo.gl/YBw9PkbhCEg5Zom37',
    null,
    null,
    'f/5, 1/4000 sec, ISO 500.'),
  new Picture(14,
    'bike-1.jpg',
    null,
    '20th of April, 2024',
    'Union Boulevard',
    'https://maps.app.goo.gl/jrqEgrzxVspMfSTM9',
    null,
    null,
    'f/1.8, 1/800 sec, ISO 250.'),
  new Picture(15,
    'tesla-1.jpg',
    null,
    '20th of April, 2024',
    'Union Boulevard',
    'https://maps.app.goo.gl/yfwhpKDBGY1nrmtc8',
    null,
    null,
    'f/1.8, 1/400 sec, ISO 100.'),
  new Picture(16,
    'garlic-1.jpg',
    null,
    '20th of April, 2024',
    'Local Farmers\' Market',
    'https://maps.app.goo.gl/f44jdQatbMr6R7Tj9',
    null,
    null,
    'f/1.8, 1/1600 sec, ISO 160.'),
  new Picture(17,
    'selfie-1.jpg',
    null,
    '20th of April, 2024',
    'Union Boulevard',
    'https://maps.app.goo.gl/fugDzdxRf3Mg5MU49',
    null,
    null,
    'f/2.2, 1/2000 sec, ISO 1600.'),
  new Picture(18,
    'bike-girl-1.jpg',
    null,
    '20th of April, 2024',
    'Union Boulevard',
    'https://maps.app.goo.gl/J2LBhTnQ6nfQwMRr9',
    null,
    null,
    'f/1.8, 1/1250 sec, ISO 250.'),
  new Picture(19,
    'old-man-1.jpg',
    null,
    '20th of April, 2024',
    'Union Boulevard',
    'https://maps.app.goo.gl/f3MqbLFxuE7KsaMG8',
    null,
    null,
    'f/1.8, 1/1250 sec, ISO 100.'),
  new Picture(20,
    'union-boulevard-1.jpg',
    null,
    '20th of April, 2024',
    'Union Boulevard',
    'https://maps.app.goo.gl/f3MqbLFxuE7KsaMG8',
    null,
    null,
    'f/4, 1/1000 sec, ISO 100.'),
  new Picture(21,
    'union-boulevard-2.jpg',
    null,
    '20th of April, 2024',
    'Union Boulevard',
    'https://maps.app.goo.gl/f3MqbLFxuE7KsaMG8',
    null,
    null,
    'f/4.5, 1/640 sec, ISO 100.'),
  new Picture(22,
    'bmw-1.jpg',
    null,
    '20th of April, 2024',
    'Union Boulevard',
    'https://maps.app.goo.gl/6nY3XAcv7G5CzPVb6',
    null,
    null,
    'f/1.8, 1/400 sec, ISO 400.'),
  new Picture(23,
    'guy-waiting-flower-1.jpg',
    null,
    '20th of April, 2024',
    'Union Plaza',
    'https://maps.app.goo.gl/pKVSidFra17wrP86A',
    null,
    null,
    'f/3.2, 1/250 sec, ISO 100.'),
  new Picture(24,
    'guy-on-bike-1.jpg',
    null,
    '20th of April, 2024',
    'Union Plaza',
    'https://maps.app.goo.gl/vyiQHuiZMkpcQpQg7',
    null,
    null,
    'f/3.2, 1/250 sec, ISO 100.'),
  new Picture(25,
    'guy-back-shot-1.jpg',
    null,
    '20th of April, 2024',
    'Old Town',
    'https://maps.app.goo.gl/em2HScuwVp86VLWc9',
    null,
    null,
    'f/1.8, 1/800 sec, ISO 100.'),
  new Picture(26,
    'accordion-player.jpg',
    null,
    '20th of April, 2024',
    'Old Town',
    'https://maps.app.goo.gl/CZpC9P2EE3W5wJpTA',
    null,
    null,
    'f/3.2, 1/200 sec, ISO 500.'),
  new Picture(27,
    'street-performer-1.jpg',
    null,
    '20th of April, 2024',
    'Old Town',
    'https://maps.app.goo.gl/5NDjPqsgXzo6DJJT7',
    null,
    null,
    'f/1.8, 1/1000 sec, ISO 320.'),
  new Picture(28,
    'guy-tunnel-1.jpg',
    null,
    '20th of April, 2024',
    'Old Town',
    'https://maps.app.goo.gl/5NDjPqsgXzo6DJJT7',
    null,
    null,
    'f/1.8, 1/500 sec, ISO 160.'),
  new Picture(29,
    'street-performer-2.jpg',
    null,
    '20th of April, 2024',
    'Victory Street',
    'https://maps.app.goo.gl/KFBdsabApQnhEAh36',
    null,
    null,
    'f/4, 1/640 sec, ISO 250.'),
  new Picture(30,
    'palace-hall.jpg',
    null,
    '20th of April, 2024',
    'The Palace Hall',
    'https://maps.app.goo.gl/8Z1VGR9VoWRa8KrN8',
    null,
    null,
    'f/4, 1/1000 sec, ISO 200.'),
  new Picture(31,
    'street-performer-3.jpg',
    null,
    '20th of April, 2024',
    'Victory Street',
    'https://maps.app.goo.gl/LQciTZtApnDyStHbA',
    null,
    null,
    'f/1.8, 1/800 sec, ISO 250.'),
  new Picture(32,
    'jandarmeria-back-shot-2.jpg',
    null,
    '20th of April, 2024',
    'Victory Street',
    'https://maps.app.goo.gl/mJRWJKFsF2f2zAEG6',
    null,
    null,
    'f/1.8, 1/1250 sec, ISO 250.'),
  new Picture(33,
    'bancorex-headquarters-1.jpg',
    null,
    '20th of April, 2024',
    'Bancorex Headquarters',
    'https://maps.app.goo.gl/v4BrzBkJHeYwByis5',
    null,
    null,
    'f/4, 1/400 sec, ISO 125.'),
  new Picture(34,
    'bancorex-headquarters-2.jpg',
    null,
    '20th of April, 2024',
    'Bancorex Headquarters',
    'https://maps.app.goo.gl/v4BrzBkJHeYwByis5',
    null,
    null,
    'f/4, 1/400 sec, ISO 125.'),
  new Picture(35,
    'national-museum-of-romanian-history-1.jpg',
    null,
    '20th of April, 2024',
    'National Museum of Romanian History',
    'https://maps.app.goo.gl/QR8J4ucDQSFz8ocJ9',
    null,
    null,
    'f/1.8, 1/500 sec, ISO 3200.'),
  new Picture(36,
    'old-town-1.jpg',
    null,
    '20th of April, 2024',
    'Old Town',
    'https://maps.app.goo.gl/eWTzKTxqPBqE6RPGA',
    null,
    null,
    'f/1.8, 1/400 sec, ISO 320.'),
  new Picture(37,
    'union-plaza-1.jpg',
    null,
    '20th of April, 2024',
    'Union Plaza',
    'https://maps.app.goo.gl/jxoHwJGAnMmuAHae8',
    null,
    null,
    'f/1.8, 1/400 sec, ISO 400.'),
  new Picture(38,
    'union-plaza-2.jpg',
    null,
    '20th of April, 2024',
    'Union Plaza',
    'https://maps.app.goo.gl/jxoHwJGAnMmuAHae8',
    null,
    null,
    'f/1.8, 1/400 sec, ISO 1250.'),
  new Picture(39,
    'union-plaza-3.jpg',
    null,
    '20th of April, 2024',
    'Union Plaza',
    'https://maps.app.goo.gl/jxoHwJGAnMmuAHae8',
    null,
    null,
    'f/1.8, 1/400 sec, ISO 160.'),
  new Picture(40,
    'union-plaza-4.jpg',
    null,
    '20th of April, 2024',
    'Union Plaza',
    'https://maps.app.goo.gl/jxoHwJGAnMmuAHae8',
    null,
    null,
    'f/1.8, 1/400 sec, ISO 2500.'),
  new Picture(41,
    'union-plaza-5.jpg',
    null,
    '20th of April, 2024',
    'Union Plaza',
    'https://maps.app.goo.gl/1pJAZcB2cBTJhVw76',
    null,
    null,
    'f/1.8, 1/80 sec, ISO 1250.'),
];
